config/routes.rb
module BaseRouting
  module RoutingMethods
    def cycle_routes
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :subjects, only: [:index, :show], path: 'assuntos', controller: 'cycles/subjects' do
        resources :comments, only: [:index, :create, :update], controller: 'cycles/subjects/comments', path: 'comentarios' do
          resources :comments, only: [:index], path: 'respostas', controller: 'cycles/subjects/comments'
          resources :likes, only: [:create, :destroy], path: 'like', controller: 'cycles/subjects/comments/likes'
          resources :dislikes, only: [:create, :destroy], path: 'dislike', controller: 'cycles/subjects/comments/dislikes'
        end
      end

      resources :materials, only: [:index], path: 'biblioteca', controller: 'cycles/materials'
      resources :vocabularies, only: [:index], path: 'glossário', controller: 'cycles/vocabularies'

      resources :plugin_relations, only: [:show], path: 'plugins', controller: 'cycles/plugin_relations'
    end
  end
end

include BaseRouting::RoutingMethods

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin/admin_users/sessions',
    registrations: 'admin/admin_users/registrations',
    passwords: 'admin/admin_users/passwords'
  }

  get 'admin', to: 'admin/cycles#index'
  namespace :admin do
    resources :admin_users, path: 'administradores' do
      collection do
        delete "bulk_destroy", to: "admin_users#bulk_destroy", as: :bulk_destroy
      end
    end
    resources :blog_posts, path: 'blog'
    resources :credits, path: 'creditos'
    resources :static_pages, only: [:show, :new, :create, :edit, :update, :destroy], path: 'institucional'
    resources :credit_categories, only: [:new, :create, :edit, :update, :destroy], path: 'categorias-de-credito'
    resources :cycles, only: [:index, :show, :new, :create, :edit, :update], path: 'temas' do
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :users, only: [:index, :show], controller: 'cycles/users', path: 'usuarios'
      resources :plugin_relations, only:[:show], path: 'plugins', controller: 'cycles/plugin_relations' do
        resources :subjects, controller: 'cycles/plugin_relations/subjects', path: 'temas' do
          resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:show] do
            resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:new, :create]
          end
        end
        resources :materials, path: 'materiais', controller: 'cycles/materials'
        resources :vocabularies, path: 'termos', controller: 'cycles/vocabularies'
        resources :settings, only: [:create, :update], controller: 'cycles/plugin_relations/settings'
        resources :compilation_files, only: [:update], controller: 'cycles/plugin_relations/compilation_files'
      end
      resources :charts, only: [:index], controller: 'cycles/charts', path: 'graficos-personalizados'
    end
    match 'users/:id/comments', to: 'users#user_comment_csv', via: :get

    resources :users, only: [:index, :show], path: 'usuarios'
    resources :settings, only: [:index, :update], path: 'configuracoes'
    resources :social_links, only: [:create, :update, :destroy]

    resources :grid_highlights, only: [:index, :update], path: 'destaques'
    post "destaques/:id", to: 'grid_highlights#update'

    get 'tinymce_s3_upload/signed_urls' => 'amazon_s3_tinymce#index', as: :signed_urls
    resources :statistics, only: [:index] , path: 'stats'
    match 'stats/users', to: 'statistics#users_csv', via: :get
    match 'stats/comments', to: 'statistics#comments_csv', via: :get
  end

  namespace :api do
    namespace :v1 do
      namespace :users do
        match '/sign_in', to: 'sessions#create', via: :post
        match '/sign_out', to: 'sessions#destroy', via: :delete
        match '/sign_up', to: 'registrations#new', via: :get
        match '/facebook', to: 'oauths#facebook', via: :post
        match '/twitter', to: 'oauths#twitter', via: :post
        resources :notifications
      end
      resource :user, only: [:show]
      resource :registrations, only: [:create, :update], path: 'users', controller: 'users/registrations'
      resource :passwords, only: [:create], path: 'passwords', controller: 'users/passwords'

      # resources :profiles, only: [:index]
      resources :cycles, only: [:index, :show]
      resources :settings, only: [:index]
      resources :subjects, only: [:index, :show] do
        resources :comments, only: [:index, :create, :update, :destroy] do
          resources :comments, only: [:index, :create], as: :children
          resources :likes, only: [:create], controller: 'cycles/subjects/comments/likes'
          match '/likes', to: 'cycles/subjects/comments/likes#destroy', via: :delete
          resources :dislikes, only: [:create], controller: 'cycles/subjects/comments/dislikes'
          match '/dislikes', to: 'cycles/subjects/comments/dislikes#destroy', via: :delete
        end
      end
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/busca', to: 'search#show', as: :search, via: :get

  resources :blog_posts, path: 'blog'

  # get 'termos-de-uso' => 'static_pages#use_terms', as: :use_terms
  # get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  resources :static_pages, only: [:show], path: 'institucional'
  resources :credits, only:[:index], path: 'creditos'

  match '/:uf/cities', to: 'cities#index', via: :get
  match '/:profile_id/profiles', to: 'profiles#index', via: :get

  match '/ping', to: 'ping#show', via: :get

  root 'cycles#index'

  resources :cycles, only: [:show], path: 'temas' do
    cycle_routes
  end
  resources :cycles, only: [:show], path: '' do
    cycle_routes
  end
end

app/views/layouts/shared/_base_header.html.slim
#simple-menu
  nav.navbar.navbar-default.navbar-fixed-top.base-navbar
    .container
      .navbar-header.non-cycle-header
        button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#base-navbar-collapse" aria-expanded="false"
          span class="sr-only" Toggle navigation
          span class="icon-bar"
          span class="icon-bar"
          span class="icon-bar"
        = link_to root_path, class: 'navbar-brand' do
          = image_tag('mudamos-logo.svg')

      .collapse.navbar-collapse#base-navbar-collapse.non-cycle-header
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            = render 'layouts/shared/user_dropdown'
            = render 'layouts/shared/user_notification'
          - else
            li= link_to 'ENTRAR', '#', onclick: 'javascript:document.open_login();'
          li.icon-item.search style="opacity: 0" = link_to '#' do
            i.icon-search
        ul.nav.navbar-nav.navbar-center.non-cycle
          - if params[:controller] == 'cycles' and params[:action] == 'index'
            li= link_to 'SOBRE', '#', :'scroll-to' => '#about'
            li= link_to 'DESTAQUES', '#', :'scroll-to' => '#highlights'
          - else
            li= link_to 'SOBRE', root_path + '#about'
            li= link_to 'DESTAQUES', root_path + '#highlights'
          li.dropdown class=("dropup" if params[:controller] == 'cycles' and params[:action] == 'index')
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, role: 'button' do
              | TEMAS
              span.caret
            ul.dropdown-menu
              - @cycles.each do |c|
                li= link_to c.title, c
              li= link_to 'Reforma Política do Século 21', 'https://plataformabrasil.org.br/', target: '_blank'
          li= link_to 'BLOG', blog_posts_path
    = render 'layouts/search_bar'

- if params[:controller] == 'cycles' and params[:action] == 'index'
  = javascript_include_tag 'base_header_scroll_to'

/ javascript:
/   $(document).ready(function() {
/     $('#simple-menu').sidr();
/   });

app/views/layouts/shared/_cycle_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .row.primary-navbar style="background-color: #{@cycle.color}"
    .col-xs-12
      .container
        .navbar-header
          = link_to root_path, class: 'navbar-brand' do
            = image_tag('mudamos-logo.svg')
        ul.nav.navbar-nav.navbar-center
          p.navbar-cycle-text= @cycle.title

        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            / li.navbar-text= "Olá, #{current_user.name}"
            / li= link_to 'SAIR', destroy_user_session_path, method: :delete
            = render 'layouts/shared/user_dropdown'
            = render 'layouts/shared/user_notification'
          - else
            li= link_to 'ENTRAR', '#', onclick: 'javascript:document.open_login();'
          li.icon-item.search= link_to '#' do
            i.icon-search
  .row.secondary-navbar
    .col-xs-12.dark-bg
      .container
        ul.nav.navbar-nav.navbar-center.cycle-header
          li= link_to 'HOME', cycle_path(@cycle)
          - if @cycle.current_phase.present?
            - if @cycle.current_phase.plugin.plugin_type == 'Discussão'
              li= link_to 'ASSUNTOS', cycle_subjects_path(@cycle)
            - elsif @cycle.current_phase.plugin.plugin_type == 'Relatoria'
              li= link_to 'RELATORIA', cycle_plugin_relation_path(@cycle, @cycle.current_phase.plugin_relation)
          - if @cycle.blog_plugin.present?
            li= link_to 'BLOG', cycle_blog_posts_path(@cycle)

          - if @cycle.past_phases.any? or @cycle.plugins.where(plugin_type: ["Biblioteca", "Glossário"]).where.not(plugin_type: 'Blog').any?
            li.dropdown
              = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, role: 'button' do
                | INFORME-SE
                .span.caret
              ul.dropdown-menu.cycle
                - @cycle.past_phases.each do |pp|
                  - if pp.plugin.plugin_type == 'Discussão'
                    li= link_to 'ASSUNTOS', cycle_subjects_path(@cycle)
                  - elsif pp.plugin.plugin_type == 'Relatoria'
                    li= link_to 'RELATORIA', cycle_plugin_relation_path(@cycle, @cycle.current_phase.plugin_relation)
                - if @cycle.plugins.where(plugin_type: 'Biblioteca').any?
                  li= link_to 'BIBLIOTECA', cycle_materials_path(@cycle)
                - if @cycle.plugins.where(plugin_type: 'Glossário').any?
                  li= link_to 'GLOSSÁRIO', cycle_vocabularies_path(@cycle)
  = render 'layouts/search_bar'

app/views/layouts/shared/_flash_messages.js.erb
<% flash.each do |error, msg| %>
  document.flash_message("<%= j(msg).gsub('\n', ' - ').html_safe %>", "<%= error %>");
<% end %>

app/views/layouts/shared/_footer.html.slim
nav.navbar.footer-nav
  .container
    ul.nav.navbar-nav
      / li= link_to 'Termos de uso', use_terms_path
      / li= link_to 'Política de Privacidade', privacy_policy_path
      - @footer_pages.each do |page|
        li= link_to page.name, page
    ul.nav.navbar-nav.navbar-right
      - if @cycle
        li= link_to 'Críticas e Sugestões', cycle_blog_post_path(@cycle, BlogPost.find('sobre-a-ombudsperson-silvia-ramos'))
      li= link_to 'Creditos', credits_path
      li= link_to 'Contato', 'mailto:contato@mudamos.org'
  .container
    hr
  .container
    ul.nav.navbar-nav
      / li= link_to image_tag('creative_commons.png'), '#'
      li= render 'outsiders/creative_commons'
    ul.nav.navbar-nav.navbar-right.social-footer-links
      - @social_links.each do |sl|
        li= link_to sl.link, target: '_blank' do
          i class=sl.icon_class
/ section.container#footer
/   .row
/     .col-xs-4.col-lg-1
/       =link_to 'CONTATO', '#'
/     .col-xs-4.col-lg-2
/       =link_to 'TERMOS DE USO', '#'
/     .col-xs-2.col-lg-3
/       =link_to 'POLÍTICA DE PRIVACIDADE' , '#'
/   .row
/     hr
/   .row
/     .col-xs-2.col-lg-4
/       =link_to image_tag('creative_commons.png'), '#'
/     .col-xs-2.col-lg-1.col-lg-offset-7
/       =link_to (fa_icon 'facebook', class: 'fa-2x') , '#'
/       | &nbsp; &nbsp;
/       =link_to (fa_icon 'twitter', class: 'fa-2x') , '#'

app/views/layouts/shared/_modal.html.slim
- content ||= ''

.modal.fade id=(modal_id || 'modal') role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-dialog class=("modal-#{size || 'md'}")
    .modal-content.container = content.html_safe
    .close type='button' data-dismiss='modal'
      i.icon-close

app/views/layouts/shared/_phase_description.html.slim
.row.phase
  div class="pull-#{align}"
    / .phase-title= "Fase #{i + 1}"
    .date
      = "De #{phase.initial_date.to_short_date}"
      br
      = "Até #{phase.final_date.to_short_date}"

  .phase-description class="text-#{align} pull-#{align}"
    .row
      .col-xs-12 class="text-#{align}"
        i class="icon-#{(phase.plugin_relation.plugin.icon_class)}" class="pull-#{align}" style="color: #{phase.cycle.color}"
        div class="pull-#{align}"
          .status style="color: #{phase.cycle.color}" = phase.current_status
    .row
      .col-xs-12
        h3.phase-plugin-title class=align = phase.name
        p= phase.description.html_safe
    .row.cycle-more
      .col-xs-12
        - if phase.plugin.plugin_type == 'Relatoria' and phase.initial_date < Time.zone.now
          = link_to 'Saiba mais', cycle_plugin_relation_path(@cycle, @cycle.plugin_relations.find('relatoria')), style: "color: #{@cycle.color}"
        - elsif phase.plugin.plugin_type == 'Discussão' and phase.initial_date < Time.zone.now
          = link_to 'Saiba mais', [@cycle, :subjects], style: "color: #{@cycle.color}"
        / = link_to 'Saiba mais', cycle_blog_post_path(@cycle, BlogPost.find_by_slug('como-funciona-o-ciclo-sobre-seguranca-publica')), style: "color: #{@cycle.color}"

app/views/layouts/shared/_user_dropdown.html.slim
li.dropdown.user-dropdown class=("dropup" if params[:controller] == 'cycles' and params[:action] == 'index')
  = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, role: 'button' do
    = image_tag current_user.picture, class: 'user-menu-image'
    = current_user.name.split(' ').first
    span.caret
  ul.dropdown-menu
    li= link_to 'EDITAR PERFIL', edit_user_registration_path
    li= link_to 'SAIR', destroy_user_session_path, method: :delete

app/views/layouts/shared/_user_notification.html.slim
li.icon-item.notification
  a.notification-icon
    i.icon-notifications
  span.notification-message= @notifications.unread.count
  ul.notification-dropdown
    - @notifications.each do |n|
      li.notification-dropdown-item
        a href="#{n.notification.view_url}"
          .notification-media
            = image_tag(n.notification.picture_url)
          .notification-content
            p= n.notification.title.html_safe
            span= "há #{distance_of_time_in_words(n.created_at, Time.zone.now)}"

javascript:
  $(function(){
    notify.user.init();
  });

app/views/layouts/shared/vocabulary_modal.html.slim
.row
  .col-xs-12
    .section-title style=("border-color: #{@cycle.color}" if @cycle) = @subject.title
.row
  .col-xs-12.subject-tag-description
    = @subject.tag_description.html_safe

- if @subject.vocabulary.present?
  .row
    .col-xs-12.vocabulary-modal-link
      span= "Leia mais no "
      = link_to "Glossário", "#{cycle_vocabularies_path(@cycle)}##{@subject.vocabulary.id}"