config/routes.rb
module BaseRouting
  module RoutingMethods
    def cycle_routes
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :subjects, only: [:index, :show], path: 'assuntos', controller: 'cycles/subjects' do
        resources :comments, only: [:index, :create, :update], controller: 'cycles/subjects/comments', path: 'comentarios' do
          resources :comments, only: [:index], path: 'respostas', controller: 'cycles/subjects/comments'
          resources :likes, only: [:create, :destroy], path: 'like', controller: 'cycles/subjects/comments/likes'
          resources :dislikes, only: [:create, :destroy], path: 'dislike', controller: 'cycles/subjects/comments/dislikes'
        end
      end

      resources :materials, only: [:index], path: 'biblioteca', controller: 'cycles/materials'
      resources :vocabularies, only: [:index], path: 'glossário', controller: 'cycles/vocabularies'

      resources :plugin_relations, only: [:show], path: 'plugins', controller: 'cycles/plugin_relations'
    end
  end
end

include BaseRouting::RoutingMethods

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin/admin_users/sessions',
    registrations: 'admin/admin_users/registrations',
    passwords: 'admin/admin_users/passwords'
  }

  get 'admin', to: 'admin/cycles#index'
  namespace :admin do
    resources :admin_users, path: 'administradores' do
      collection do
        delete "bulk_destroy", to: "admin_users#bulk_destroy", as: :bulk_destroy
      end
    end
    resources :blog_posts, path: 'blog'
    resources :credits, path: 'creditos'
    resources :static_pages, only: [:show, :new, :create, :edit, :update, :destroy], path: 'institucional'
    resources :credit_categories, only: [:new, :create, :edit, :update, :destroy], path: 'categorias-de-credito'
    resources :cycles, only: [:index, :show, :new, :create, :edit, :update], path: 'temas' do
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :users, only: [:index, :show], controller: 'cycles/users', path: 'usuarios'
      resources :plugin_relations, only:[:show], path: 'plugins', controller: 'cycles/plugin_relations' do
        resources :subjects, controller: 'cycles/plugin_relations/subjects', path: 'temas' do
          resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:show] do
            resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:new, :create]
          end
        end
        resources :materials, path: 'materiais', controller: 'cycles/materials'
        resources :vocabularies, path: 'termos', controller: 'cycles/vocabularies'
        resources :settings, only: [:create, :update], controller: 'cycles/plugin_relations/settings'
        resources :compilation_files, only: [:update], controller: 'cycles/plugin_relations/compilation_files'
      end
      resources :charts, only: [:index], controller: 'cycles/charts', path: 'graficos-personalizados'
    end
    match 'users/:id/comments', to: 'users#user_comment_csv', via: :get

    resources :users, only: [:index, :show], path: 'usuarios'
    resources :settings, only: [:index, :update], path: 'configuracoes'
    resources :social_links, only: [:create, :update, :destroy]

    resources :grid_highlights, only: [:index, :update], path: 'destaques'
    post "destaques/:id", to: 'grid_highlights#update'

    get 'tinymce_s3_upload/signed_urls' => 'amazon_s3_tinymce#index', as: :signed_urls
    resources :statistics, only: [:index] , path: 'stats'
    match 'stats/users', to: 'statistics#users_csv', via: :get
    match 'stats/comments', to: 'statistics#comments_csv', via: :get
  end

  namespace :api do
    namespace :v1 do
      namespace :users do
        match '/sign_in', to: 'sessions#create', via: :post
        match '/sign_out', to: 'sessions#destroy', via: :delete
        match '/sign_up', to: 'registrations#new', via: :get
        match '/facebook', to: 'oauths#facebook', via: :post
        match '/twitter', to: 'oauths#twitter', via: :post
        resources :notifications
      end
      resource :user, only: [:show]
      resource :registrations, only: [:create, :update], path: 'users', controller: 'users/registrations'
      resource :passwords, only: [:create], path: 'passwords', controller: 'users/passwords'

      # resources :profiles, only: [:index]
      resources :cycles, only: [:index, :show]
      resources :settings, only: [:index]
      resources :subjects, only: [:index, :show] do
        resources :comments, only: [:index, :create, :update, :destroy] do
          resources :comments, only: [:index, :create], as: :children
          resources :likes, only: [:create], controller: 'cycles/subjects/comments/likes'
          match '/likes', to: 'cycles/subjects/comments/likes#destroy', via: :delete
          resources :dislikes, only: [:create], controller: 'cycles/subjects/comments/dislikes'
          match '/dislikes', to: 'cycles/subjects/comments/dislikes#destroy', via: :delete
        end
      end
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/busca', to: 'search#show', as: :search, via: :get

  resources :blog_posts, path: 'blog'

  # get 'termos-de-uso' => 'static_pages#use_terms', as: :use_terms
  # get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  resources :static_pages, only: [:show], path: 'institucional'
  resources :credits, only:[:index], path: 'creditos'

  match '/:uf/cities', to: 'cities#index', via: :get
  match '/:profile_id/profiles', to: 'profiles#index', via: :get

  match '/ping', to: 'ping#show', via: :get

  root 'cycles#index'

  resources :cycles, only: [:show], path: 'temas' do
    cycle_routes
  end
  resources :cycles, only: [:show], path: '' do
    cycle_routes
  end
end

app/models/search.rb
class Search
  def self.find value
    h = Hash.new

    cycles = Cycle.cycle_search(value)
    h[:cycles] = cycles unless cycles.empty?

    subjects = Subject.subject_search(value)
    h[:subjects] = subjects unless subjects.empty?

    blog_posts = BlogPost.blog_post_search(value)
    h[:blog_posts] = blog_posts unless blog_posts.empty?

    # users = User.user_search(User.encrypt_name(value))
    # h[:users] = users unless users.empty?

    vocabularies = Vocabulary.vocabulary_search(value)
    h[:vocabularies] = vocabularies unless vocabularies.empty?

    materials = Material.material_search(value)
    h[:materials] = materials unless materials.empty?

    comments = Comment.comments_search(value)
    # comments = Comment.where(id: (comments.pluck(:id) + comments_users.pluck(:id)))

    h[:comments] = comments unless comments.empty?

    h
  end

  def self.translate_key k
    case k
    when :users
      'Usuários'
    when :cycles
      'Temas'
    when :subjects
      'Assuntos'
    when :blog_posts
      'Blog'
    when :vocabularies
      'Glossário'
    when :materials
      'Biblioteca'
    when :comments
      'Comentários'
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def show
    @results = Search.find params[:search]

    render partial: 'layouts/search_results'
  end

end

app/views/search/_blog_post_thumb.html.slim
.row.blog-post-search-result
  .col-xs-2
    = image_tag blog_post.picture(:thumb)
  .col-xs-10
    h2= link_to blog_post.title, blog_post_dependent_path(blog_post)
    span= "Blog #{blog_post.cycle_name}"
    .blog-bottom-area= blog_post.content.html_safe

app/views/search/_comment_thumb.html.slim
- liked = user_signed_in? ? comment.liked_by?(current_user) : false
- disliked = user_signed_in? ? comment.disliked_by?(current_user) : false
- color ||= comment.subject.plugin_relation.cycle.color

.row id=("comment-#{comment.id}") data-cycle-slug="#{comment.subject.plugin_relation.cycle.slug}" data-subject-slug="#{comment.subject.slug}" data-base-url="#{cycle_subject_url(comment.subject.plugin_relation.cycle, comment.subject)}" data-comment-share-params="comments=#{comment.parents_url_params}" class="#{'selected-comment' if @selected_comment_id == comment.id.to_s}"
  .col-xs-12
    .row.reading-comment style="border-color: #{color}"
      .col-xs-2.user-area style="border-color: #{color}"
        .img
          = image_tag(comment.photo)
        h5= comment.author
        -if comment.user.profile.present?
          label style="color: #{color}" Setor:
          p= comment.user.profile.name
        - if comment.user.sub_profile.present?
          label style="color: #{color}" Subsetor:
          p= comment.user.sub_profile.name
      .col-xs-10.content-area
        .content
          .comment-content.comment-dotdotdot
            - if comment.content.include? '<p>'
              = comment.content.gsub('<p></p>', '').gsub('<p>&nbsp;</p>', '').gsub("\r\n", '').html_safe
            - else
              p= comment.content.gsub('<p></p>', '').gsub('<p>&nbsp;</p>', '').gsub("\r\n", '').html_safe
          = link_to 'Continuar Lendo [...]', cycle_subject_path(comment.subject.plugin_relation.cycle, comment.subject, comments: comment.parents_url_params), style: "color: #{color}"
        .extra-area style="border-color: #{color}"
          i.icon-clock style= "color: #{color}"
          span= comment.created_at.to_short_date
          span= comment.created_at.to_short_time
          - unless comment.depth > 2
            span style= "color: #{color}"
              b= comment.descendants.count
              = " respostas"

          span.like_button style="color: #{color};" class="#{user_signed_in? ? 'toggleable' : ''}" onclick="#{'document.open_login(); document.flash_message("Você precisa estar logado para curtir um comentário.", "error")' unless user_signed_in?}"
            i.icon-like class="#{liked ? 'toggled' : ''}"
          span.like_counter
            ="%02d" % comment.likes_count
          span.dislike_button style="color: #{color};" class="#{user_signed_in? ? 'toggleable' : ''}" onclick="#{'document.open_login(); document.flash_message("Você precisa estar logado para não curtir um comentário.", "error")' unless user_signed_in?}"
            i.icon-dislike class="#{disliked ? 'toggled' : ''}"
          span.dislike_counter
            ="%02d" % comment.dislikes_count
          / span.share-comment
          /   button
          /     i.icon-share
          /   span.share_list
          /     a.facebook href="#"
          /       i.icon-facebook
          /     a.copy-to-clipboard
          /       span Copiar Link

app/views/search/_cycle_thumb.html.slim
.row.cycle-search-result
  .col-xs-2
    = image_tag cycle.picture(:thumb)
  .col-xs-10
    h2= link_to cycle.name, cycle_path(cycle)
    .cycle-bottom-description= cycle.description.html_safe

app/views/search/_material_thumb.html.slim
.material-search-result
  .material.row
    .col-xs-1
      .icon style="border-color: #{material.cycle.color}"
        i class="icon-#{material.category_icon}" style="color: #{material.cycle.color}"
    .col-xs-6.basic-content
      = link_to material.title, material.external_link, target: "_blank"
      - if material.publishing_date or material.source
        .row
          .col-xs-12
            - if material.publishing_date
              span= material.publishing_date.to_short_date
            - if material.source
              span= "Fonte: #{material.source}"
      - if material.author
        .row
          .col-xs-12
            span= "Autor: #{material.author}"
    - if material.description
      .col-xs-5.with-left-line style="border-color: #{material.cycle.color}"
        p= material.description

app/views/search/_subject_thumb.html.slim
.subject-search-result
  h2.title= link_to subject.title, cycle_subject_path(subject.plugin_relation.cycle, subject)
  span= "Tema: #{subject.plugin_relation.cycle.name}"
  h4.enunciation= subject.enunciation
  h3.question= subject.question

app/views/search/_vocabulary_thumb.html.slim
.vocabulary-search-result
  .letter-results
    .row
      .col-xs-1
        .big-letter.text-left style="color: #{vocabulary.cycle.color}; border-color: #{vocabulary.cycle.color}" = vocabulary.first_letter
      .col-xs-11
        .row
          .col-xs-3.vocabulary-title.text-left id=(vocabulary.id) = vocabulary.title
          .col-xs-9.vocabulary-description.text-left style="border-color: #{vocabulary.cycle.color}" = vocabulary.description.html_safe