config/routes.rb
module BaseRouting
  module RoutingMethods
    def cycle_routes
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :subjects, only: [:index, :show], path: 'assuntos', controller: 'cycles/subjects' do
        resources :comments, only: [:index, :create, :update], controller: 'cycles/subjects/comments', path: 'comentarios' do
          resources :comments, only: [:index], path: 'respostas', controller: 'cycles/subjects/comments'
          resources :likes, only: [:create, :destroy], path: 'like', controller: 'cycles/subjects/comments/likes'
          resources :dislikes, only: [:create, :destroy], path: 'dislike', controller: 'cycles/subjects/comments/dislikes'
        end
      end

      resources :materials, only: [:index], path: 'biblioteca', controller: 'cycles/materials'
      resources :vocabularies, only: [:index], path: 'glossário', controller: 'cycles/vocabularies'

      resources :plugin_relations, only: [:show], path: 'plugins', controller: 'cycles/plugin_relations'
    end
  end
end

include BaseRouting::RoutingMethods

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin/admin_users/sessions',
    registrations: 'admin/admin_users/registrations',
    passwords: 'admin/admin_users/passwords'
  }

  get 'admin', to: 'admin/cycles#index'
  namespace :admin do
    resources :admin_users, path: 'administradores' do
      collection do
        delete "bulk_destroy", to: "admin_users#bulk_destroy", as: :bulk_destroy
      end
    end
    resources :blog_posts, path: 'blog'
    resources :credits, path: 'creditos'
    resources :static_pages, only: [:show, :new, :create, :edit, :update, :destroy], path: 'institucional'
    resources :credit_categories, only: [:new, :create, :edit, :update, :destroy], path: 'categorias-de-credito'
    resources :cycles, only: [:index, :show, :new, :create, :edit, :update], path: 'temas' do
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :users, only: [:index, :show], controller: 'cycles/users', path: 'usuarios'
      resources :plugin_relations, only:[:show], path: 'plugins', controller: 'cycles/plugin_relations' do
        resources :subjects, controller: 'cycles/plugin_relations/subjects', path: 'temas' do
          resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:show] do
            resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:new, :create]
          end
        end
        resources :materials, path: 'materiais', controller: 'cycles/materials'
        resources :vocabularies, path: 'termos', controller: 'cycles/vocabularies'
        resources :settings, only: [:create, :update], controller: 'cycles/plugin_relations/settings'
        resources :compilation_files, only: [:update], controller: 'cycles/plugin_relations/compilation_files'
      end
      resources :charts, only: [:index], controller: 'cycles/charts', path: 'graficos-personalizados'
    end
    match 'users/:id/comments', to: 'users#user_comment_csv', via: :get

    resources :users, only: [:index, :show], path: 'usuarios'
    resources :settings, only: [:index, :update], path: 'configuracoes'
    resources :social_links, only: [:create, :update, :destroy]

    resources :grid_highlights, only: [:index, :update], path: 'destaques'
    post "destaques/:id", to: 'grid_highlights#update'

    get 'tinymce_s3_upload/signed_urls' => 'amazon_s3_tinymce#index', as: :signed_urls
    resources :statistics, only: [:index] , path: 'stats'
    match 'stats/users', to: 'statistics#users_csv', via: :get
    match 'stats/comments', to: 'statistics#comments_csv', via: :get
  end

  namespace :api do
    namespace :v1 do
      namespace :users do
        match '/sign_in', to: 'sessions#create', via: :post
        match '/sign_out', to: 'sessions#destroy', via: :delete
        match '/sign_up', to: 'registrations#new', via: :get
        match '/facebook', to: 'oauths#facebook', via: :post
        match '/twitter', to: 'oauths#twitter', via: :post
        resources :notifications
      end
      resource :user, only: [:show]
      resource :registrations, only: [:create, :update], path: 'users', controller: 'users/registrations'
      resource :passwords, only: [:create], path: 'passwords', controller: 'users/passwords'

      # resources :profiles, only: [:index]
      resources :cycles, only: [:index, :show]
      resources :settings, only: [:index]
      resources :subjects, only: [:index, :show] do
        resources :comments, only: [:index, :create, :update, :destroy] do
          resources :comments, only: [:index, :create], as: :children
          resources :likes, only: [:create], controller: 'cycles/subjects/comments/likes'
          match '/likes', to: 'cycles/subjects/comments/likes#destroy', via: :delete
          resources :dislikes, only: [:create], controller: 'cycles/subjects/comments/dislikes'
          match '/dislikes', to: 'cycles/subjects/comments/dislikes#destroy', via: :delete
        end
      end
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/busca', to: 'search#show', as: :search, via: :get

  resources :blog_posts, path: 'blog'

  # get 'termos-de-uso' => 'static_pages#use_terms', as: :use_terms
  # get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  resources :static_pages, only: [:show], path: 'institucional'
  resources :credits, only:[:index], path: 'creditos'

  match '/:uf/cities', to: 'cities#index', via: :get
  match '/:profile_id/profiles', to: 'profiles#index', via: :get

  match '/ping', to: 'ping#show', via: :get

  root 'cycles#index'

  resources :cycles, only: [:show], path: 'temas' do
    cycle_routes
  end
  resources :cycles, only: [:show], path: '' do
    cycle_routes
  end
end

app/controllers/admin/cycles/blog_posts_controller.rb
class Admin::Cycles::BlogPostsController < Admin::ApplicationController
  before_action :set_plugin_relations, only: [:new, :edit, :create, :update]

  def index
    @blog_posts = @cycle.blog_posts
  end

  def show
    @blog_post = BlogPost.find params[:id]
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new blog_post_params

    if @blog_post.save
      flash[:success] = "Post criado com sucesso."
      redirect_to [:admin, @cycle, @blog_post]
    else
      flash[:error] = "Ocorreu algum erro ao criar o post."
      render :new
    end
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    @blog_post.assign_attributes blog_post_params

    fast_updated = (@blog_post.highlighted_changed? or @blog_post.active_changed?)

    if @blog_post.save
      flash[:success] = "Post atualizado com sucesso."

      if fast_updated
        redirect_to request.referrer
      else
        redirect_to [:admin, @cycle, @blog_post]
      end
    else
      flash[:error] = "Ocorreu algum erro ao atualizar o post."
      render :edit
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.destroy
      flash[:success] = "Post apagado com sucesso."
    else
      flash[:error] = "Ocorreu algum erro ao apagar o post."
    end
    redirect_to [:admin, @cycle, :blog_posts]
  end

  private

    def set_plugin_relations
      @plugin_relations_cycles = PluginRelation.blog.map{|x| [x.cycle.name,x.id]}
    end

    def blog_post_params
      params.require(:blog_post).permit(
        :active,
        :highlighted,
        :title,
        :content,
        :plugin_relation_id,
        :picture,
        :release_date
      )
    end
end

app/controllers/admin/cycles/charts_controller.rb
class Admin::Cycles::ChartsController < Admin::ApplicationController

  def index

  end

end

app/controllers/admin/cycles/materials_controller.rb
class Admin::Cycles::MaterialsController < Admin::ApplicationController
  before_action :set_params, only: [:create, :update]

  def index
    @materials = @plugin_relation.materials.page(params[:page]).per(qty)
  end

  def show
  end

  def new
    @material = @plugin_relation.materials.new
  end

  def create
    @material = @plugin_relation.materials.new material_params
    @material.cycle = @cycle

    if @material.save
      flash[:success] = "Material criado com sucesso."
      redirect_to [:admin, @cycle, @plugin_relation, :materials]
    else
      flash[:error] = "Ocorreu algum erro ao criar o material."
      render :new
    end
  end

  def edit
    @material = @plugin_relation.materials.find params[:id]
  end

  def update
    @material = @plugin_relation.materials.find params[:id]

    if @material.update_attributes material_params
      flash[:success] = "Material atualizado com sucesso."
      redirect_to [:admin, @cycle, @plugin_relation, :materials]
    else
      flash[:error] = "Ocorreu algum erro ao atualizar o material."
      render :edit
    end
  end

  def destroy
    @material = @plugin_relation.materials.find params[:id]

    if @material.destroy
      flash[:success] = "Material excluído com sucesso."
    else
      flash[:error] = "Erro ao excluir material."
    end

    redirect_to [:admin, @cycle, @plugin_relation, :materials]
  end

  private

    def set_params
      [:themes, :keywords].each do |attr|
        next if params[:material]["#{attr.to_s.singularize}_ids"].blank?

        params[:material][attr] = params[:material]["#{attr.to_s.singularize}_ids"].reject { |x| x.blank? }.map { |x| x.is_number? ? Material.tags_on(attr).find(x.to_i) : x }.join(';')
      end
    end

    def material_params
      params.require(:material).permit(
        :author,
        :title,
        :source,
        :category,
        :description,
        :position,
        :themes,
        :keywords
      )
    end
end

app/controllers/admin/cycles/plugin_relations/compilation_files_controller.rb
class Admin::Cycles::PluginRelations::CompilationFilesController < Admin::ApplicationController

  def update
    @plugin_relation = @cycle.plugin_relations.find params[:plugin_relation_id]
    @compilation_file = @plugin_relation.compilation_file
    if @compilation_file.id.to_s != params[:id].to_s
      flash[:error] = "Página inválida."
      redirect_to admin_path
    else
      if @compilation_file.update_attributes compilation_params
        flash[:success] = "Alterações da Relatoria efetuadas com sucesso."
      else
        flash[:error] = "Ocorreu algum erro ao salvar as alterações da Relatoria."
      end

      redirect_to [:admin, @cycle, @plugin_relation]
    end
  end

  private

    def compilation_params
      params.require(:compilation_file).permit(
        :title1,
        :title2,
        :title3,
        :file
      )
    end
end

app/controllers/admin/cycles/plugin_relations/settings_controller.rb
class Admin::Cycles::PluginRelations::SettingsController < Admin::ApplicationController

  def create
    @setting = Setting.new setting_params

    if @setting.save
      flash[:success] = "Conteúdo alterado com sucesso."
    else
      flash[:error] = "Houve algum erro ao alterar o conteúdo"
    end

    redirect_to [:admin, @cycle, @plugin_relation]
  end

  def update
    @setting = Setting.find params[:id]

    if @setting.update_attributes setting_params
      flash[:success] = "Conteúdo alterado com sucesso."
    else
      flash[:error] = "Houve algum erro ao alterar o conteúdo"
    end

    redirect_to [:admin, @cycle, @plugin_relation]
  end

  private

    def setting_params
      params.require(:setting).permit(
        :key,
        :value,
        :picture
      )
    end
end

app/controllers/admin/cycles/plugin_relations/subjects/comments_controller.rb
class Admin::Cycles::PluginRelations::Subjects::CommentsController < Admin::ApplicationController
  before_action :set_subject
  before_action :set_parent_comment, if: -> { params[:comment_id].present? }

  def index
    if params[:comment_id].present?
      @comment = @subject.comments.find params[:comment_id]
      @comments = @comment.children
    else
      @comments = @subject.comments.roots
    end

  end

  def show
    @comment = @subject.comments.find params[:id]

    params[:order] ||= 'created_at'
    @comments = @comment.children.order("#{params[:order]} DESC").page(params[:page]).per(qty)

    @comment_profile_count_in_range = @comments.includes(:user, user: :profile).reject { |x| x.user.profile.blank? }.group_by { |x| x.user.profile.name }
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @parent_comment.children.new comment_params
    @comment.user = User.unscoped.where(is_admin: true).first
    @comment.subject = @subject

    if @comment.save
      flash[:success] = "Resposta criada com sucesso."
      redirect_to [:admin, @cycle, @plugin_relation, @subject, @parent_comment]
    else
      flash[:error] = "Ocorreu algum erro ao criar o comentário."
      render :new
    end
  end

  private

    def comment_params
      params.require(:comment).permit(
        :content
      )
    end

    def set_subject
      @subject = @plugin_relation.subjects.find(params[:subject_id])
    end

    def set_parent_comment
      @parent_comment = @subject.comments.find params[:comment_id]
    end

end

app/controllers/admin/cycles/plugin_relations/subjects_controller.rb
class Admin::Cycles::PluginRelations::SubjectsController < Admin::ApplicationController
  before_action :set_vocabulary_plugin_relation, only: [:new, :create, :edit, :update]
  def index
    @subjects = @plugin_relation.subjects.page(params[:page]).per(qty)
  end

  def show
    @subject = @plugin_relation.subjects.find params[:id]

    params[:order] ||= 'created_at'
    @comments = @subject.comments.order("#{params[:order]} DESC")

    @comment_profile_count_in_range = @comments.includes(:user, user: :profile).group_by { |x| x.user.profile.name }

    @comments = @comments.page(params[:page]).per(qty)
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = @plugin_relation.subjects.new subject_params

    if @subject.save
      flash[:success] = "Assunto criado com sucesso."
      redirect_to [:admin, @cycle, @plugin_relation, :subjects]
    else
      flash[:error] = "Ocorreu algum erro ao criar o assunto."
      render :new
    end
  end

  def edit
    @subject = @plugin_relation.subjects.find params[:id]
  end

  def update
    @subject = @plugin_relation.subjects.find params[:id]

    if @subject.update_attributes subject_params
      flash[:success] = "Assunto atualizado com sucesso."

      if subject_params[:file].present?
        redirect_to [:admin, @cycle, @cycle.plugin_relations.find('relatoria')]
      else
        redirect_to [:admin, @cycle, @plugin_relation, :subjects]
      end
    else
      flash[:error] = "Ocorreu algum erro ao atualizar o assunto."

      if subject_params[:file].present?
        redirect_to [:admin, @cycle, @cycle.plugin_relations.find('relatoria')]
      else
        render :edit
      end
    end
  end

  def destroy
    @subject = @plugin_relation.subjects.find params[:id]

    if @subject.destroy
      flash[:success] = "Assunto apagado com sucesso."
    else
      flash[:error] = "Ocorreu algum erro ao apagar o assunto."
    end

    redirect_to [:admin, @cycle, @plugin_relation, :subjects]
  end

  private

    def set_vocabulary_plugin_relation
      @vocabulary_plugin_relation = @cycle.plugin_relations.find_by_slug('glossario')
    end

    def subject_params
      params.require(:subject).permit(
        :enunciation,
        :question,
        :title,
        :vocabulary_id,
        :tag_description,
        :file
      )
    end
end

app/controllers/admin/cycles/plugin_relations_controller.rb
class Admin::Cycles::PluginRelationsController < Admin::ApplicationController
  def show
    @plugin_relation = @cycle.plugin_relations.find params[:id]

    case @plugin_relation.plugin.plugin_type
    when 'Discussão'
      redirect_to [:admin, @cycle, @plugin_relation, :subjects]
    when 'Relatoria'
      render 'compilation'
    when 'Biblioteca'
      redirect_to [:admin, @cycle, @plugin_relation, :materials]
    when 'Glossário'
      redirect_to [:admin, @cycle, @plugin_relation, :vocabularies]
    when 'Blog'
      redirect_to [:admin, @cycle, :blog_posts]
    end
  end

end

app/controllers/admin/cycles/users_controller.rb
class Admin::Cycles::UsersController < Admin::ApplicationController
  def index
    @users = Kaminari.paginate_array(@cycle.users.sort_by { |x| x.name }).page(params[:page]).per(qty)

    respond_to do |format|
      format.html  { }
      format.csv   { send_csv @cycle.users.to_csv, "usuarios" }
    end
  end

  def show
    @user = @cycle.users.find params[:id]
    # @cycles = @user.cycles_interacted.page(params[:page]).per(qty)

    params[:order] ||= 'created_at'
    @comments = @cycle.comments.where(user_id: @user.id).order("#{params[:order]} DESC").page(params[:page]).per(qty)
  end

  def user_comment_csv
    user = User.find params[:id]
    @comments = user.comments

    respond_to do |format|
      format.csv { send_csv @comments.to_csv, "comentarios" }
    end
  end
end

app/views/admin/cycles/vocabularies/_form.html.slim
= semantic_form_for [:admin, @cycle, @plugin_relation, @vocabulary] do |f|
  .row
    .col-xs-12
      = f.input :title, label: 'Título'
      = f.input :description, label: 'Texto', input_html: { class: 'tinymce', rows: 5, style: 'height: auto;' }
  .row.form-row
    .col-xs-12
      button type="submit" Salvar

javascript:
  $(document).ready(fuction(){
    admin.edit.init('#vocabulary_description');
  })

app/views/admin/cycles/vocabularies/edit.html.slim
- breadcrumb :edit_vocabulary, @vocabulary, @cycle, @plugin_relation

= render 'admin/cycles/vocabularies/form'

app/views/admin/cycles/vocabularies/index.html.slim
- breadcrumb :vocabularies, @cycle, @plugin_relation

#glossario-biblioteca
  #accordion-parent.accordion
    / .accordion-group
    /   .accordion-trigger
    /     a.accordion-toggle.collapsed data-parent="#accordion-parent" data-toggle="collapse" href="#collapseOne"
    /       .row
    /         .col-xs-11
    /           h4 Título
    /           .line
    /         .col-xs-1
    /           i.icon-close
    /   #collapseOne.accordion-body.collapse
    /     .accordion-content
    /       .row
    /         .col-xs-12
    /           .card-module
    /             i.icon-edit
    /             #edit-title.editable-content.mce-hidden
    /               p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem sed nesciunt atque, saepe iusto ipsum, et quae, numquam voluptatum a assumenda blanditiis dolore! Ea fugit molestias quisquam, minima adipisci quidem.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos praesentium quas sunt, adipisci commodi maxime unde modi ex ipsum doloribus doloremque quae tempore reiciendis quam voluptatum, eius vitae temporibus accusantium.
    /             .pull-right
    /               a.btn.hidden.mce-button Salvar Alterações
    / .accordion-group
    /   .accordion-trigger
    /     a.accordion-toggle.collapsed data-parent="#accordion-parent" data-toggle="collapse" href="#collapseTwo"
    /       .row
    /         .col-xs-11
    /           h4 Texto Inicial
    /           .line
    /         .col-xs-1
    /           i.icon-close
    /   #collapseTwo.accordion-body.collapse
    /     .accordion-content
    /       .row
    /         .col-xs-12
    /           .card-module
    /             i.icon-edit
    /             #edit-text.editable-content
    /               p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem sed nesciunt atque, saepe iusto ipsum, et quae, numquam voluptatum a assumenda blanditiis dolore! Ea fugit molestias quisquam, minima adipisci quidem.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos praesentium quas sunt, adipisci commodi maxime unde modi ex ipsum doloribus doloremque quae tempore reiciendis quam voluptatum, eius vitae temporibus accusantium.
    /             .pull-right
    /               a.btn.hidden.mce-button Salvar Alterações
    / .accordion-group
    /   .accordion-trigger
    /     a.accordion-toggle.collapsed data-parent="#accordion-parent" data-toggle="collapse" href="#collapseThree"
    /       .row
    /         .col-xs-11
    /           h4 Nota
    /           .line
    /         .col-xs-1
    /           i.icon-close
    /   #collapseThree.accordion-body.collapse
    /     .accordion-content
    /       .row
    /         .col-xs-12
    /           .card-module
    /             i.icon-edit
    /             #edit-note.editable-content
    /               p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem sed nesciunt atque, saepe iusto ipsum, et quae, numquam voluptatum a assumenda blanditiis dolore! Ea fugit molestias quisquam, minima adipisci quidem.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos praesentium quas sunt, adipisci commodi maxime unde modi ex ipsum doloribus doloremque quae tempore reiciendis quam voluptatum, eius vitae temporibus accusantium.
    /             .pull-right
    /               a.btn.hidden.mce-button Salvar Alterações
    .accordion-group
      .accordion-trigger
        a.accordion-toggle data-parent="#accordion-parent" data-toggle="collapse" href="#collapseFour"
          .row
            .col-xs-11
              h4 Verbetes
              .line
            .col-xs-1
              i.icon-close
      #collapseFour.accordion-body.collapse.in
        .accordion-content
          .row
            .col-xs-12
              .card-module
                b.status-number= @vocabularies.total_count
                | Número total de verbetes
                .row
                  .col-xs-12
                    / - ('a'..'z').each do |letter|
                    /   = link_to "#{letter}", '#', class: "letter-link"
                    / .pull-right
                    /   a.btn Exportar CSV
                    .pull-right
                      / a.btn Adicionar Verbete
                      = link_to 'Adicionar Verbete', new_admin_cycle_plugin_relation_vocabulary_path, class: 'btn'
                  //  - ('a'..'z').each do |letter|
                  //    = link_to "#{letter}", class: 'letter-link', style: "border-color: #{@cycle.color}", disabled: not(@vocabularies.pluck(:first_letter).include?(letter)) do
                  //      .background style="background-color: #{@cycle.color}"
                  //      = letter
          .row
            .col-xs-12
              #administrators.card-module
                .filters.clearfix
                  = render 'admin/shared/page_quantity'
                table
                  thead
                    tr
                      th Título
                      th Texto
                      th Ações
                  tbody
                    - @vocabularies.each do |v|
                      tr
                        td= v.title
                        td.comments-dotdotdot
                          p.comment= v.description.html_safe
                          a.read-more Ler Mais
                          a.read-less Esconder
                        td
                          select.select-actions.select2-disabled
                            option.disabled selected="true" mais...
                            option value=edit_admin_cycle_plugin_relation_vocabulary_path(@cycle, @plugin_relation, v) Editar
                            option value=admin_cycle_plugin_relation_vocabulary_path(@cycle, @plugin_relation, v) method="delete" Excluir
          = render 'admin/shared/pagination', collection: @vocabularies


javascript:
  admin.edit.init();
javascript:
  tinyMCE.init({
    selector: ".editable-content",
    plugins: ["autolink lists link image preview anchor", "fullscreen hr code visualblocks visualchars", "table paste"],
    file_browser_callback: function(field_name, url, type, win) {
      return this.set_amazon_direct_upload($('#' + field_name));
    },
    toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    content_css: "#{ActionController::Base.helpers.asset_path('tinymce.css')}",
    setup: function(ed) {
        ed.on('init', function(e) {
            e.target.hide();
        });
    }
  });
  javascript:
    $(document).ready(function() {
      $(".comments-dotdotdot").dotdotdot({
        //after: "a.read-more",
        height: parseInt( $('.comments-dotdotdot').css('line-height'), 10) * 3,
        lastCharacter: {
            remove: [ ' ', ',', ';', '.', '!', '?' ],
            noEllipsis: []
        }
      });

      //$('a.read-more').on( 'click', function(event) {
      //  event.preventDefault();
      //  $(this).parent().trigger("destroy");
      //  $(this).hide();
      //  $(this).parent().find('a.read-less').show();
      //});

      //$('a.read-less').on( 'click', function(event) {
      //  event.preventDefault();
      //  $(this).hide();
      //  $(this).parent().parent().find('a.read-more').show();
      //});
    });

app/views/admin/cycles/vocabularies/new.html.slim
- breadcrumb :new_vocabulary, @cycle, @plugin_relation

= render 'admin/cycles/vocabularies/form'

app/views/admin/cycles/vocabularies/show.html.slim
h1 Admin::Cycles::Vocabularies#show
p Find me in app/views/admin/cycles/vocabularies/show.html.slim