config/routes.rb
module BaseRouting
  module RoutingMethods
    def cycle_routes
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :subjects, only: [:index, :show], path: 'assuntos', controller: 'cycles/subjects' do
        resources :comments, only: [:index, :create, :update], controller: 'cycles/subjects/comments', path: 'comentarios' do
          resources :comments, only: [:index], path: 'respostas', controller: 'cycles/subjects/comments'
          resources :likes, only: [:create, :destroy], path: 'like', controller: 'cycles/subjects/comments/likes'
          resources :dislikes, only: [:create, :destroy], path: 'dislike', controller: 'cycles/subjects/comments/dislikes'
        end
      end

      resources :materials, only: [:index], path: 'biblioteca', controller: 'cycles/materials'
      resources :vocabularies, only: [:index], path: 'glossário', controller: 'cycles/vocabularies'

      resources :plugin_relations, only: [:show], path: 'plugins', controller: 'cycles/plugin_relations'
    end
  end
end

include BaseRouting::RoutingMethods

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin/admin_users/sessions',
    registrations: 'admin/admin_users/registrations',
    passwords: 'admin/admin_users/passwords'
  }

  get 'admin', to: 'admin/cycles#index'
  namespace :admin do
    resources :admin_users, path: 'administradores' do
      collection do
        delete "bulk_destroy", to: "admin_users#bulk_destroy", as: :bulk_destroy
      end
    end
    resources :blog_posts, path: 'blog'
    resources :credits, path: 'creditos'
    resources :static_pages, only: [:show, :new, :create, :edit, :update, :destroy], path: 'institucional'
    resources :credit_categories, only: [:new, :create, :edit, :update, :destroy], path: 'categorias-de-credito'
    resources :cycles, only: [:index, :show, :new, :create, :edit, :update], path: 'temas' do
      resources :blog_posts, path: 'blog', controller: 'cycles/blog_posts'
      resources :users, only: [:index, :show], controller: 'cycles/users', path: 'usuarios'
      resources :plugin_relations, only:[:show], path: 'plugins', controller: 'cycles/plugin_relations' do
        resources :subjects, controller: 'cycles/plugin_relations/subjects', path: 'temas' do
          resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:show] do
            resources :comments, controller: 'cycles/plugin_relations/subjects/comments', path: 'comentarios', only: [:new, :create]
          end
        end
        resources :materials, path: 'materiais', controller: 'cycles/materials'
        resources :vocabularies, path: 'termos', controller: 'cycles/vocabularies'
        resources :settings, only: [:create, :update], controller: 'cycles/plugin_relations/settings'
        resources :compilation_files, only: [:update], controller: 'cycles/plugin_relations/compilation_files'
      end
      resources :charts, only: [:index], controller: 'cycles/charts', path: 'graficos-personalizados'
    end
    match 'users/:id/comments', to: 'users#user_comment_csv', via: :get

    resources :users, only: [:index, :show], path: 'usuarios'
    resources :settings, only: [:index, :update], path: 'configuracoes'
    resources :social_links, only: [:create, :update, :destroy]

    resources :grid_highlights, only: [:index, :update], path: 'destaques'
    post "destaques/:id", to: 'grid_highlights#update'

    get 'tinymce_s3_upload/signed_urls' => 'amazon_s3_tinymce#index', as: :signed_urls
    resources :statistics, only: [:index] , path: 'stats'
    match 'stats/users', to: 'statistics#users_csv', via: :get
    match 'stats/comments', to: 'statistics#comments_csv', via: :get
  end

  namespace :api do
    namespace :v1 do
      namespace :users do
        match '/sign_in', to: 'sessions#create', via: :post
        match '/sign_out', to: 'sessions#destroy', via: :delete
        match '/sign_up', to: 'registrations#new', via: :get
        match '/facebook', to: 'oauths#facebook', via: :post
        match '/twitter', to: 'oauths#twitter', via: :post
        resources :notifications
      end
      resource :user, only: [:show]
      resource :registrations, only: [:create, :update], path: 'users', controller: 'users/registrations'
      resource :passwords, only: [:create], path: 'passwords', controller: 'users/passwords'

      # resources :profiles, only: [:index]
      resources :cycles, only: [:index, :show]
      resources :settings, only: [:index]
      resources :subjects, only: [:index, :show] do
        resources :comments, only: [:index, :create, :update, :destroy] do
          resources :comments, only: [:index, :create], as: :children
          resources :likes, only: [:create], controller: 'cycles/subjects/comments/likes'
          match '/likes', to: 'cycles/subjects/comments/likes#destroy', via: :delete
          resources :dislikes, only: [:create], controller: 'cycles/subjects/comments/dislikes'
          match '/dislikes', to: 'cycles/subjects/comments/dislikes#destroy', via: :delete
        end
      end
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/busca', to: 'search#show', as: :search, via: :get

  resources :blog_posts, path: 'blog'

  # get 'termos-de-uso' => 'static_pages#use_terms', as: :use_terms
  # get 'politica-de-privacidade' => 'static_pages#privacy_policy', as: :privacy_policy
  resources :static_pages, only: [:show], path: 'institucional'
  resources :credits, only:[:index], path: 'creditos'

  match '/:uf/cities', to: 'cities#index', via: :get
  match '/:profile_id/profiles', to: 'profiles#index', via: :get

  match '/ping', to: 'ping#show', via: :get

  root 'cycles#index'

  resources :cycles, only: [:show], path: 'temas' do
    cycle_routes
  end
  resources :cycles, only: [:show], path: '' do
    cycle_routes
  end
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id                   :integer          not null, primary key
#  plugin_relation_id   :integer
#  title                :string
#  content              :text
#  picture              :string
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  is_readonly          :boolean
#  release_date         :datetime
#  slug                 :string
#  deleted_at           :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  author_name          :string
#  active               :boolean          default(TRUE)
#  highlighted          :boolean          default(FALSE)
#

class BlogPost < ActiveRecord::Base
  acts_as_paranoid
  extend FriendlyId
  friendly_id :title

  include PgSearch
  pg_search_scope :blog_post_search,
                  against: [
                    :title,
                    :content,
                    :author_name
                  ],
                  ignoring: :accents,
                  using: [:tsearch, :trigram]

  belongs_to :plugin_relation

  has_many :grid_highlights, as: :target_object

  delegate :cycle, :plugin, :related, to: :plugin_relation, allow_nil: true

  has_attached_file :picture, preserve_files: true, styles: { header: "1920x500#", thumb: "570x430#" }, processors: [:thumbnail]

  default_scope { order('release_date DESC, created_at DESC') }

  scope :active, -> { where{ active == true } }
  scope :released, -> { active.where{ release_date < DateTime.now } }
  scope :highlights, -> {
    highlights = released.where{ highlighted == true }.order('RANDOM()').limit(3)

    unless highlights.any?
      highlights = released.limit(3)
    end

    highlights
  }



  validates_attachment :picture, presence: true, content_type: { content_type: ["image/jpeg", "image/gif", "image/jpg", "image/png"] }

  validates_presence_of :title, :content, :release_date
  validate :plugin_type_is_blog?, on: :create, if: -> { self.plugin }

  def attributes_to_filter (filter = [])
    attrs = self.attributes.except(
      "picture_file_size",
      "picture_updated_at",
      "picture_content_type",
      "picture_file_name",
      "deleted_at",
      "created_at",
      "updated_at"
    ).keys

    attrs.push 'picture'
    attrs
  end

  def release_date= value
    if value.is_a? String
      begin
        value = Date.parse(value)
      rescue Exception => e
        value = nil
      end
    end

    super
  end

  def color
    if self.cycle.present?
      self.cycle.color
    else
      nil
    end
  end

  def cycle_name
    self.cycle.present? ? self.cycle.name : "Mudamos"
  end

  def author_name
    super || 'Mudamos'
  end

  private

    def plugin_type_is_blog?
      errors.add(plugin.plugin_type, 'plugin must be a Blog type') if plugin.plugin_type != 'Blog'
    end

  #TODO
  #has_many :blog_comments
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < Admin::ApplicationController
  before_action :set_plugin_relations, only: [:new, :edit, :create, :update]

  def index
    if @cycle
      @blog_posts = @cycle.blog_posts
    else
      @blog_posts = BlogPost.all
    end
  end

  def show
    @blog_post = BlogPost.find params[:id]
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new blog_post_params

    if @blog_post.save
      flash[:success] = "Post criado com sucesso."
      redirect_to [:admin, @blog_post]
    else
      flash[:error] = "Ocorreu algum erro ao criar o post."
      render :new
    end
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    @blog_post.assign_attributes blog_post_params

    fast_updated = (@blog_post.highlighted_changed? or @blog_post.active_changed?)

    if @blog_post.save
      flash[:success] = "Post atualizado com sucesso."

      if fast_updated
        redirect_to request.referrer
      else
        redirect_to [:admin, @blog_post]
      end
    else
      flash[:error] = "Ocorreu algum erro ao atualizar o post."
      render :edit
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.destroy
      flash[:success] = "Post apagado com sucesso."
    else
      flash[:error] = "Ocorreu algum erro ao apagar o post."
    end
    redirect_to [:admin, :blog_posts]
  end

  private

    def set_plugin_relations
      @plugin_relations_cycles = PluginRelation.blog.map{|x| [x.cycle.name,x.id]}
    end

    def blog_post_params
      params.require(:blog_post).permit(
        :active,
        :highlighted,
        :title,
        :content,
        :plugin_relation_id,
        :picture,
        :release_date
      )
    end
end

app/controllers/admin/cycles/blog_posts_controller.rb
class Admin::Cycles::BlogPostsController < Admin::ApplicationController
  before_action :set_plugin_relations, only: [:new, :edit, :create, :update]

  def index
    @blog_posts = @cycle.blog_posts
  end

  def show
    @blog_post = BlogPost.find params[:id]
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def create
    @blog_post = BlogPost.new blog_post_params

    if @blog_post.save
      flash[:success] = "Post criado com sucesso."
      redirect_to [:admin, @cycle, @blog_post]
    else
      flash[:error] = "Ocorreu algum erro ao criar o post."
      render :new
    end
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    @blog_post.assign_attributes blog_post_params

    fast_updated = (@blog_post.highlighted_changed? or @blog_post.active_changed?)

    if @blog_post.save
      flash[:success] = "Post atualizado com sucesso."

      if fast_updated
        redirect_to request.referrer
      else
        redirect_to [:admin, @cycle, @blog_post]
      end
    else
      flash[:error] = "Ocorreu algum erro ao atualizar o post."
      render :edit
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.destroy
      flash[:success] = "Post apagado com sucesso."
    else
      flash[:error] = "Ocorreu algum erro ao apagar o post."
    end
    redirect_to [:admin, @cycle, :blog_posts]
  end

  private

    def set_plugin_relations
      @plugin_relations_cycles = PluginRelation.blog.map{|x| [x.cycle.name,x.id]}
    end

    def blog_post_params
      params.require(:blog_post).permit(
        :active,
        :highlighted,
        :title,
        :content,
        :plugin_relation_id,
        :picture,
        :release_date
      )
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_highlights

  def index
    @blog_posts = BlogPost.released.page params[:page]
    @big_blog_post = BlogPost.highlights.sample
  end

  def show
    @blog_post = BlogPost.find params[:id]
  end

  private

    def set_highlights
      @posts_highlights = BlogPost.highlights
    end
end

app/controllers/cycles/blog_posts_controller.rb
class Cycles::BlogPostsController < ApplicationController
  before_action :set_cycle
  before_action :set_highlights

  def index
    @blog_posts = @cycle.blog_posts.released.page params[:page]
    @big_blog_post = @blog_posts.highlights.sample
    render 'blog_posts/index'
  end

  def show
    @blog_post = @cycle.blog_posts.find params[:id]
    render 'blog_posts/show'
  end

  private

    def set_cycle
      @cycle = Cycle.find params[:cycle_id]
    end

    def set_highlights
      @posts_highlights = @cycle.blog_posts.highlights
    end
end

app/views/admin/blog_posts/_form.html.slim
javascript:
  tinyMCE.init({
    selector: "textarea#blog_post_content",
    plugins: ["autolink lists link image preview anchor", "fullscreen hr code visualblocks visualchars", "table paste"],
    file_browser_callback: function(field_name, url, type, win) {
      return this.set_amazon_direct_upload($('#' + field_name));
    },
    toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    content_css: "#{ActionController::Base.helpers.asset_path('tinymce.css')}",
    setup: function(ed){
      ed.on('init', function(){
        $(ed.getBody()).on('focus', function(){
          parent = $(this).parents('li#blog_post_content_input:first');
          parent.find('p.inline-errors').slideUp(300, function(){
            $(this).remove();
          })
        })
      })
    }
  });

  $(document).ready(function(){
    $('#blog_post_release_date').datepicker({
      language: 'pt-BR',
      orientation: 'auto bottom',
      format: 'dd/mm/yyyy',
      todayHighlight: false,
      startDate: '-2y',
      endDate: '+2y'
    })
  })

= semantic_form_for [:admin, @blog_post], as: :blog_post do |f|
  .row
    .col-xs-8
      .row
        .col-xs-12
          .title
            h2 Selecione uma imagem
      .row
        .col-xs-12
          .file-input-image-container
            = f.input :picture, as: :file, label: false, input_html: { class: 'image-upload' }
            .file-input-image
              = image_tag(f.object.picture? ? f.object.picture(:medium) : nil)
          button.upload-image
            .arrow
            .background
            | Adicionar Foto
          - if f.object.errors[:picture].any?
            p.inline-errors= f.object.errors[:picture].first
      .row
        .col-xs-12
          .title
            h2 Título
      .row
        .col-xs-12
          = f.input :title, label: false, placeholder: 'Título'
      .row
        .col-xs-12
          .title
            h2 Conteúdo do Post
      .row
        .col-xs-12
          = f.input :content, label: false, input_html: { class: "tinymce", rows: 3 }
      .row
        .col-xs-12
          = f.button onclick: 'javascript: document.start_loading();'
    .col-xs-4
      .row
        .col-xs-12
          = f.input :plugin_relation_id,
                    label: false,
                    as: :select,
                    collection: @plugin_relations_cycles,
                    include_blank: 'Ciclo'
      .row
        .col-xs-12
          = f.input :release_date, label: false, placeholder: 'Selecione uma data', input_html: { value: (f.object.release_date.strftime('%d/%m/%Y') if f.object.release_date.present?) }, as: :string

app/views/admin/blog_posts/create.js.erb
<%= render 'layouts/shared/flash_messages' %>

$(document).ready(function() {
  <% if @blog_post.errors.any? %>
    document.stop_loading();
    document.set_errors(<%= @blog_post.errors.to_json.html_safe %>, $('form#new_blog_post'), "blog_post");
  <% else %>
    location.href = "/admin/blog"
  <% end %>
});

app/views/admin/blog_posts/edit.html.slim
- breadcrumb :edit_blog_post, @blog_post
/ section.not-centered#cycle-description
/   .container
/     .row
/       .col-xs-12.text-center
/         h1 Edição de Post

= render 'admin/blog_posts/form'

app/views/admin/blog_posts/index.html.slim
- breadcrumb :blog_posts

.row
  .col-xs-12
    .card-module
      .pull-right
        = link_to 'Criar Post', [:new, :admin, :blog_post], class: 'btn'
      p
        b.status-number= @blog_posts.count
        | Número total de Posts no Blog
      .filters
        span.active Mais Recentes

= render partial: 'admin/shared/blog_posts/thumb', collection: @blog_posts, as: :blog_post

/ section.not-centered#cycle-description
/   .container
/     h1 Lista de Posts no Blog
/     a.btn.btn-default.btn-primary href="#{new_admin_blog_post_path}" role="button" Criar novo Post

/     table.table.table-striped
/       thead
/         tr
/           th Ciclo
/           th Titulo
/           th Data de Publicação
/           th
/       tbody
/         - @blog_posts.each do |bp|
/           tr
/             td
/               bp = bp.cycle.nil? ? 'não informado' : bp.cycle.name
/             td
/               bp = bp.title
/             td
/               bp = bp.release_date
/             td
/               bp
/                 a.btn.btn-default.btn-warning href="#{edit_admin_blog_post_path(bp)}" role="button" Editar

app/views/admin/blog_posts/new.html.slim
- breadcrumb :new_blog_post

= render 'admin/blog_posts/form'

app/views/admin/blog_posts/show.html.slim
- breadcrumb :blog_post, @blog_post

.row
  .col-xs-9
    .row
      .col-xs-12
        .big-image
          = image_tag @blog_post.picture(:header)
    .row
      .col-xs-12
        .card-module
          = @blog_post.content.html_safe
  .col-xs-3
    .card-module.admin-blog-show-actions.bordered
      .table
        .tr
          .td.show-action.border-right.border-bottom
            = semantic_form_for [:admin, @blog_post], method: :put do |f|
              = f.input :highlighted, as: :hidden, input_html: { value: !@blog_post.highlighted }
              button
                - if @blog_post.highlighted
                  i.icon-destacado
                  span Destacado
                - else
                  i.icon-destaque
                  span Destacar
          .td.show-action.border-bottom
            = link_to [:edit, :admin, @blog_post] do
              i.icon-edit
              span Editar
        .tr
          .td.show-action.border-right
            = semantic_form_for [:admin, @blog_post], method: :put do |f|
              = f.input :active, as: :hidden, input_html: { value: !@blog_post.active }
              button
                - if @blog_post.active
                  i.icon-desabilitar
                  span Desabilitar
                - else
                  i.icon-publicar
                  span Publicar
          .td.show-action
            = link_to [:admin, @blog_post], method: :delete do
              i.icon-deletar
              span Apagar
    .card-module.bordered.admin-blog-show-box
      b= @blog_post.cycle.name
    .card-module.bordered.admin-blog-show-box
      = "Postado em #{@blog_post.release_date.strftime('%d/%m/%Y')}"

app/views/admin/blog_posts/update.js.erb
<%= render 'layouts/shared/flash_messages' %>

$(document).ready(function() {
  <% if @blog_post.errors.any? %>
    document.stop_loading();
    document.set_errors(<%= @blog_post.errors.to_json.html_safe %>, $('form#edit_blog_post'), "blog_post");
  <% else %>
    location.href = "/admin/blog"
  <% end %>
});